name: "Check Self Hosted Runners"
description: "Check whether self hosted runner is present in org"
author: "Red Hat"
branding:
  icon: circle
  color: red
inputs:
  github_token:
    description: "Github Access Token with org and repo level permissions"
    required: true
  repository_path:
    description: |
      "Repository name with owner. For example, redhat-actions/check-self-hosted-runner. 
      It can also take the name of the org. For example , redhat-actions"
    default: ${{ github.repository }}
    required: false
  labels:
    description: "Labels in the runners to check for. For multiple labels, add all seperated by a comma(,) "
    required: false
outputs:
  runner_present:
    description: "Boolean value which signifies the presence of self hosted runner"
runs:
  using: 'node12'
  main: 'dist/index.js'